select
    person_id,
    first_name,
    last_name,
    display_first_last as full_name,
    birthdate,
    school as college, 
    country,
    last_affiliation,
    height,
    weight,
    season_exp,
    jersey,
    position,
    rosterstatus,
    games_played_current_season_flag,
    team_id,
    team_name, 
    team_abbreviation,
    team_code, 
    team_city,
    from_year,
    to_year,
    dleague_flag,
    nba_flag,
    games_played_flag,
    draft_year,
    draft_round,
    draft_number,
    greatest_75_flag

from {{ source('dbt_kraynak', 'common_player_info')}}